### ISSUE TITLE
Fresh git clone stucks after npm run start

### ISSUE THREAD

**Issue by yaroslavya** [vsavkin/router_mailapp#1]
I made a `git clone`, then `npm install`, then `npm run start`
When I go to the url, which is `http://localhost:4200/`
it shows me the "loading ..." message and the error in the console is the following:

zone.js:101 GET http://localhost:4200/traceur 404 (Not Found)

Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/traceur
        at XMLHttpRequest.wrapFn [as _onreadystatechange](http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
        at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
        at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
    Error loading http://localhost:4200/traceur
    Error loading http://localhost:4200/vendor/@angular2-material/button/button.js as "@angular2-material/button" from http://localhost:4200/app/mail.module.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/traceur(…)

I run it on windows 8 with npm 3.10.5 and nodejs v4.4.7

**Comment by yaroslavya** [comment]
Seems like the fixed version mentioned [here](https://github.com/vsavkin/router_mailapp/issues/2) fixes this issue.
